version: '3.1'

services:

  memester-database:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: memesterdev
    ports:
      - "5432:5432"

  memester-filestorage:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: memester
      MINIO_SECRET_KEY: memesterdev
    command: server /data
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3