// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        copyButton: string;
        headerControls: string;
        likeDiv: string;
        memeDiv: string;
        memeFooter: string;
        memeFooterControls: string;
        memeHeader: string;
        memeLi: string;
        nextButton: string;
        playButton: string;
        threadIdText: string;
        video: string;
        videoWrapper: string;
        wrapper: string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
