version: '3'

services:

  memester-pgsql:
    image: postgres:12-alpine
    hostname: memester-pgsql
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 9k2xn6ifm72jx9ka8k2cn6s
    volumes:
      - ./test/pgsql:/var/lib/postgresql/data

  memester-api:
    build: memester-api
    hostname: memester-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./test/logs/api:/srv/logs
      - ./test/uploaded:/media/uploaded
      - ./test/converted:/media/converted
    depends_on:
      - memester-pgsql
      - memester-redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`memester.club`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.service=api"
      - "traefik.http.services.api.loadbalancer.server.port=5000"

networks:
  default:
    external:
      name: memester-vlan