name: Docker build

on:
  push:
    branches: release/*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Enable experimental Docker features
        run: |
          echo $'{\n    "experimental": true\n}' | sudo tee /etc/docker/daemon.json && sudo service docker restart
      -
        name: Login to Docker Hub
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Add GitHub environment variables
        uses: FranzDiebold/github-env-vars-action@v1.2.1
      -
        name: Build AMD64 image
        run: |
          MEMESTER_BUILD="${GITHUB_REF_NAME/release\//}" && echo "$MEMESTER_BUILD" && docker build \
            --build-arg build="$MEMESTER_BUILD" \
            --output "type=image,push=false" \
            --tag mrosenbjerg/memester:"$MEMESTER_BUILD-alpine" \
            -f ./Docker/Build/amd64/Dockerfile \
            .
      -
        name: Push new image
        run: |
          MEMESTER_BUILD="${GITHUB_REF_NAME/release\//}" && docker push mrosenbjerg/memester:"$MEMESTER_BUILD"-alpine
      -
        name: Create and push new Docker manifest
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          MEMESTER_BUILD="${GITHUB_REF_NAME/release\//}" && \
          docker manifest create mrosenbjerg/memester:latest mrosenbjerg/memester:"$MEMESTER_BUILD"-alpine && \
          docker manifest annotate mrosenbjerg/memester:latest mrosenbjerg/memester:"$MEMESTER_BUILD"-alpine --arch amd64 --os linux && \
          docker manifest push mrosenbjerg/memester:latest
