name: Docker build

on:
  pull_request:
    branches: release/*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Login to Docker Hub
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build AMD64 image
        run: |
          MEMESTER_BUILD="${GITHUB_REF_NAME/release\//}" && docker build \
            --build-arg "build=$MEMESTER_BUILD" \
            --output "type=image,push=false" \
            --tag mrosenbjerg/memester:$MEMESTER_BUILD-alpine \
            ./Docker/Build/amd64
      -
        name: Push new image
        run: |
          docker push mrosenbjerg/memester:$MEMESTER_BUILD-alpine
      -
        name: Create and push new Docker manifest
        run: |
          docker manifest create mrosenbjerg/memester:latest \
            mrosenbjerg/memester:$MEMESTER_BUILD-alpine \
          docker manifest annotate mrosenbjerg/memester:latest mrosenbjerg/memester:$MEMESTER_BUILD-alpine --arch amd64 --os linux && \
          docker manifest push mrosenbjerg/memester:latest
