name: Docker build

on:
  pull_request:
    branches: release/*

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Login to Docker Hub
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build AMD64 image
        run: |
          MEMESTER_BUILD="${GITHUB_REF_NAME/release\//}" && DOCKER_BUILD=mrosenbjerg/memester:$MEMESTER_BUILD && docker build \
            --build-arg "build=$MEMESTER_BUILD" \
            --output "type=image,push=false" \
            --tag $DOCKER_BUILD \
            ./Docker/Build/AMD64
      -
        name: Push new image
        run: |
          docker push mrosenbjerg/memester:$MEMESTER_BUILD
      -
        name: Create and push new Docker manifest
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          docker manifest create mrosenbjerg/memester:latest \
            mrosenbjerg/memester:$MEMESTER_BUILD \
          docker manifest annotate mrosenbjerg/memester:latest mrosenbjerg/memester:$MEMESTER_BUILD --arch amd64 --os linux && \
          docker manifest push mrosenbjerg/memester:latest
