name: Docker build

on:
  pull_request:
    branches: release/*

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Login to Docker Hub
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build AMD64 image
        run: |
          MEMESTER_BUILD="${GITHUB_REF_NAME/release\//}" && docker build \
            --build-arg "build=$GITHUB_REF_NAME" \
            --output "type=image,push=false" \
            --tag mrosenbjerg/memester:amd64 \
            ./docker/gh-build/amd64
      -
        name: Push new images
        run: |
          docker push mrosenbjerg/memester:amd64
      -
        name: Create and push Docker manifest
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          docker manifest create mrosenbjerg/memester:latest \
            mrosenbjerg/memester:amd64 \
          docker manifest annotate mrosenbjerg/memester:latest mrosenbjerg/memester:amd64 --arch amd64 --os linux && \
          docker manifest push mrosenbjerg/memester:latest
